name: linting
on:
  push:
    branches: [master, feature]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
        if: always()
      - name: linting typescript
        run: yarn lint
